spring.datasource.url=jdbc:postgresql://localhost:5432/AnimalShelterDataBase
spring.datasource.username=AnimalShelter
spring.datasource.password=Postal9329809
telegram.bot.token=7132352960:AAExvpv1GfPRU_Za8Ub7T5nq1P5AIgYo41Y
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml